describe('Front', () => {
    it('deve realizar o login e preenchimento do formulário de um usuário', () => {
        cy.intercept('*/login')
        cy.visit('http://167.250.26.147:8080/sigAutomacao/app.html#/folha/pessoa')
        cy.get('#usuario').type('automacao')
        cy.get('#iPassword').type('1010')
        cy.wait(3000)
        cy.get('input.ng-scope').click()
        cy.wait(6000)
        cy.get('[name="483inputAcDescricao"]').click().type('Larissa Oliveira Mendes')
        cy.get('[name="485inputAcDescricao"]').click().type('Larissa')
        cy.get('[name="478inputText"]').click().type('37755488384')
        cy.get('[name="481inputText"]').click().type('80962086088')
        cy.get('[name="567inputDate"]').click().type('02011977')
        cy.get('[nat="cadastroPessoaFolhaDadosPessoaisSexoSelect"]').click()
        cy.get('[nat="cadastroPessoaFolhaDadosPessoaisSexoSelect"]').type('Feminino', '{downArrow}').type('{enter}')
        cy.get('[nat="cadastroPessoaFolhaDadosPessoaisEstadoCivilSelect"]').click()
        cy.get('[nat="cadastroPessoaFolhaDadosPessoaisEstadoCivilSelect"]').type('Solteiro', '{downArrow}').type('{enter}')
        cy.get('[nat="cadastroPessoaFolhaDadosPessoaisGrauInstrucaoSelect"]').click()
        cy.get('[nat="cadastroPessoaFolhaDadosPessoaisGrauInstrucaoSelect"]').type('Superior incompleto', '{downArrow}').type('{enter}')
        cy.get('[name="577inputText"]').type('Rosângela Simone  Mendes').type('{enter}')
        cy.get('[name="581inputText"]').type('Rafael Tales  Mendes').type('{enter}')
        cy.get('[name="578inputText"]').type('007.862.570-08').type('{enter}')
        cy.get('[name="582inputText"]').type('851.005.890-35').type('{enter}')
        cy.get('[name="579inputDate"]').type('12081963').type('{enter}')
        cy.get('[id="583inputDate"]').type('13111959').type('{enter}')
        cy.get('[nat="cadastroPessoaFolhaDadosPessoaisNacionalidadeSelect"]').type(' 10 - Brasileiro ','{downArrow}').type('{enter}')
        cy.get('[id="714inputAcCodigo"]').click().type('5303939').type('{enter}')
        cy.get('[id="614inputAcCodigo"]').click().type('5218508').type('{enter}')
        cy.get('[id="617inputText"]').click().type('75864970').type('{enter}')
        cy.get('[id="618inputAcCodigo"]').click().type('31966').type('{enter}')
        cy.get('[id="620inputAcCodigo"]').click().type('1066').type('{enter}')
        cy.get('[id="622inputText"]').click().type('177')
        cy.get('[id="625inputText"]').click().type('17')
        cy.get('[id="626inputText"]').click().type('2')
        cy.get('[id="627inputText"]').click().type('APT 17 A ANDAR 3')
        cy.get('[nat="cadastroPessoaFolhaCrudSalvar"]').click()
        cy.wait(3000)
        cy.get('[nat="pdBtnAlertOK"]').click()
        
    });

});